name: Validate PR title

on:
  pull_request_target:
    branches:
      - main
      - release/*
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-pr:
    uses: propeller-heads/ci-cd-templates/.github/workflows/validate-pr.yaml@main
    secrets:
      app_id: ${{ secrets.APP_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}

